---
name: ResultsDB

"on":
  pull_request:
  push:
  workflow_dispatch:
    inputs: {}

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        uses: nick-invision/retry@7152eba30c6575329ac0576536151aca5a72780e # v3
        with:
          timeout_minutes: 10
          retry_wait_seconds: 30
          max_attempts: 3
          command: >-
            sudo apt-get update
            && sudo apt-get install
            apache2-dev
            libkrb5-dev
            libldap2-dev
            libsasl2-dev

      - name: Install dependencies
        run: python -m pip install tox

      - name: Test with tox
        run: python -m tox

      - name: Run coveralls-python
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: python-${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
        run: |
          pip3 install --upgrade pip
          pip3 install --upgrade setuptools
          pip3 install --upgrade coveralls==3.2.0
          coveralls --service=github

  coveralls-finish:
    name: Finish coveralls-python
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Finished
        run: |
          pip3 install --upgrade pip
          pip3 install --upgrade setuptools
          pip3 install --upgrade coveralls
          coveralls --finish --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - Dockerfile

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: ${{ matrix.dockerfile }}
          # Ignore list:
          # * DL3041 - Specify version with dnf install -y <package>-<version>
          ignore: DL3041
          failure-threshold: warning

  image-build:
    name: Container Image Build
    needs: hadolint
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: resultsdb
      REGISTRY: quay.io/factory2
      GH_REGISTRY: ghcr.io/${{ github.actor }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry podman-compose

      - name: Update the Application Version
        run: poetry version "$(./get-version.sh)"

      - name: Get image tag from git branch
        id: get-image-tag
        run: |
          export TAG=$(sed 's/[^0-9a-zA-Z_.-]/__/g' <<< "$GITHUB_REF_NAME") &&
          echo "::set-output name=tag::$TAG"

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: >-
            ${{ steps.get-image-tag.outputs.tag }}
            ${{ github.ref == 'refs/heads/develop' && 'latest' || '' }}
            ${{ github.sha }}
          containerfiles: Dockerfile
          build-args: |
            GITHUB_SHA=${{ github.sha }}
            EXPIRES_AFTER=${{ github.ref == 'refs/heads/develop' && 'never' || '30d' }}

      - name: Log in to the image registry
        if: github.event_name == 'push' && github.actor != 'dependabot[bot]'
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603 # v1
        with:
          registry: ${{ secrets.REGISTRY_USER && env.REGISTRY || env.GH_REGISTRY }}
          username: ${{ secrets.REGISTRY_USER || github.actor }}
          password: ${{ secrets.REGISTRY_PASSWORD || secrets.GITHUB_TOKEN }}

      - name: Push Image
        if: github.event_name == 'push' && github.actor != 'dependabot[bot]'
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ secrets.REGISTRY_USER && env.REGISTRY || env.GH_REGISTRY }}
